import { ImporterPlugin } from "../../types/plugin";
import { Sparkles } from "lucide-react";
import { RecursiveTextSplitterForm } from "./RecursiveTextSplitterForm.tsx";

export const smartSegmenterPlugin: ImporterPlugin = {
    id: "smart-segmenter",
    name: "Smart Segmenter",
    description:
        "Intelligently imports any text file, automatically detecting structure and creating meaningful sections",
    icon: Sparkles,
    component: RecursiveTextSplitterForm,
    supportedExtensions: [
        "txt",
        "text",
        "md",
        "markdown",
        "csv",
        "tsv",
        "json",
        "log",
        "xml",
        "html",
        "css",
        "js",
        "ts",
        "py",
        "java",
        "cpp",
        "c",
        "h",
        "yml",
        "yaml",
        "ini",
        "conf",
        "config",
        "sh",
        "bash",
        "zsh",
        "fish",
        "ps1",
        "bat",
        "cmd",
        "r",
        "R",
        "sql",
        "rb",
        "php",
        "swift",
        "kt",
        "scala",
        "go",
        "rs",
        "m",
        "mm",
        "tex",
        "bib",
    ],
    tags: ["Universal", "Intelligent", "Flexible"],
    enabled: true,
};
