export enum EditType {
    USER_EDIT = "user-edit",
    LLM_EDIT = "llm-edit",
    LLM_GENERATION = "llm-generation",
}

export enum CodexCellTypes {
    TEXT = "text",
    PARATEXT = "paratext",
}

export enum MainChatLanguage {
    English = "English",
    Tamil = "தமிழ் (Tamil)",
    Telugu = "తెలుగు (Telugu)",
    Kannada = "ಕನ್ನಡ (Kannada)",
    Hindi = "हिन्दी (Hindi)",
    Gujarati = "ગુજરાતી (Gujarati)",
    Spanish = "Español (Spanish)",
    French = "Français (French)",
    German = "Deutsch (German)",
    Italian = "Italiano (Italian)",
    Dutch = "Nederlands (Dutch)",
    Portuguese = "Português (Portuguese)",
    Russian = "Русский (Russian)",
    Chinese = "中文 (Chinese)",
    Japanese = "日本語 (Japanese)",
    Korean = "한국어 (Korean)",
    Arabic = "العربية (Arabic)",
    Turkish = "Türkçe (Turkish)",
    Vietnamese = "Tiếng Việt (Vietnamese)",
    Thai = "ไทย (Thai)",
    Indonesian = "Bahasa Indonesia (Indonesian)",
    Malay = "Bahasa Melayu (Malay)",
    Filipino = "Filipino (Filipino)",
    Bengali = "বাংলা (Bengali)",
    Punjabi = "ਪੰਜਾਬੀ (Punjabi)",
    Marathi = "मराठी (Marathi)",
    Odia = "ଓଡ଼ିଆ (Odia)",
    Kiswahili = "Swahili (Kiswahili)",
    Urdu = "اردو (Urdu)",
    Persian = "فارسی (Persian)",
    Hausa = "Hausa",
    Amharic = "አማርኛ (Amharic)",
    Javanese = "ꦧꦱꦗꦮ (Javanese)",
    Burmese = "မြန်မာဘာသာ (Burmese)",
    Swedish = "Svenska (Swedish)",
    Norwegian = "Norsk (Norwegian)",
    Finnish = "Suomi (Finnish)",
    Danish = "Dansk (Danish)",
    Hebrew = "עברית (Hebrew)",
    Ukrainian = "Українська (Ukrainian)",
    Polish = "Polski (Polish)",
    Romanian = "Română (Romanian)",
    Czech = "Čeština (Czech)",
    Hungarian = "Magyar (Hungarian)",
    Greek = "Ελληνικά (Greek)",
    Serbian = "Српски (Serbian)",
    Croatian = "Hrvatski (Croatian)",
    Bulgarian = "Български (Bulgarian)",
    Slovak = "Slovenčina (Slovak)",
    Malayalam = "മലയാളം (Malayalam)",
    Sinhala = "සිංහල (Sinhala)",
    Khmer = "ភាសាខ្មែរ (Khmer)",
    Lao = "ພາສາລາວ (Lao)",
}

export enum ValidationErrorCode {
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED",
    UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE",
    INVALID_CONTENT = "INVALID_CONTENT",
    INSUFFICIENT_SPACE = "INSUFFICIENT_SPACE",
    SYSTEM_ERROR = "SYSTEM_ERROR",
}
