export enum EditType {
    USER_EDIT = "user-edit",
    LLM_EDIT = "llm-edit",
    LLM_GENERATION = "llm-generation",
    INITIAL_IMPORT = "initial-import", // Note: this is not fully implemented yet sources will often still have an empty edit history
    MERGE = "merge",
}

export enum CodexCellTypes {
    TEXT = "text",
    PARATEXT = "paratext",
    STYLE = "style",
}
export enum StartupFlowStates {
    LOGIN_REGISTER = "loginRegister",
    OPEN_OR_CREATE_PROJECT = "createNewProject",
    PROMPT_USER_TO_INITIALIZE_PROJECT = "promptUserToInitializeProject",
    PROMPT_USER_TO_ADD_CRITICAL_DATA = "promptUserToAddCriticalData",
    ALREADY_WORKING = "alreadyWorking",
}

export enum StartupFlowEvents {
    AUTH_LOGGED_IN = "AUTH_LOGGED_IN",
    NO_AUTH_EXTENSION = "NO_AUTH_EXTENSION",
    SKIP_AUTH = "SKIP_AUTH",
    PROJECT_CREATE_EMPTY = "PROJECT_CREATE_EMPTY",
    PROJECT_CLONE_OR_OPEN = "PROJECT_CLONE_OR_OPEN",
    BACK_TO_LOGIN = "BACK_TO_LOGIN",
    UPDATE_AUTH_STATE = "UPDATE_AUTH_STATE",
    INITIALIZE_PROJECT = "INITIALIZE_PROJECT",
    EMPTY_WORKSPACE_THAT_NEEDS_PROJECT = "EMPTY_WORKSPACE_THAT_NEEDS_PROJECT",
    VALIDATE_PROJECT_IS_OPEN = "VALIDATE_PROJECT_IS_OPEN",
    PROJECT_MISSING_CRITICAL_DATA = "PROJECT_MISSING_CRITICAL_DATA",
}
export enum MainChatLanguage {
    English = "English",
    Tamil = "தமிழ் (Tamil)",
    Telugu = "తెలుగు (Telugu)",
    Kannada = "ಕನ್ನಡ (Kannada)",
    Hindi = "हिन्दी (Hindi)",
    Gujarati = "ગુજરાતી (Gujarati)",
    Spanish = "Español (Spanish)",
    French = "Français (French)",
    German = "Deutsch (German)",
    Italian = "Italiano (Italian)",
    Dutch = "Nederlands (Dutch)",
    Portuguese = "Português (Portuguese)",
    Russian = "Русский (Russian)",
    Chinese = "中文 (Chinese)",
    Japanese = "日本語 (Japanese)",
    Korean = "한국어 (Korean)",
    Arabic = "العربية (Arabic)",
    Turkish = "Türkçe (Turkish)",
    Vietnamese = "Tiếng Việt (Vietnamese)",
    Thai = "ไทย (Thai)",
    Indonesian = "Bahasa Indonesia (Indonesian)",
    Malay = "Bahasa Melayu (Malay)",
    Filipino = "Filipino (Filipino)",
    Bengali = "বাংলা (Bengali)",
    Punjabi = "ਪੰਜਾਬੀ (Punjabi)",
    Marathi = "मराठी (Marathi)",
    Odia = "ଓଡ଼ିଆ (Odia)",
    Kiswahili = "Swahili (Kiswahili)",
    Urdu = "اردو (Urdu)",
    Persian = "فارسی (Persian)",
    Hausa = "Hausa",
    Amharic = "አማርኛ (Amharic)",
    Javanese = "ꦧꦱꦗꦮ (Javanese)",
    Burmese = "မြန်မာဘာသာ (Burmese)",
    Swedish = "Svenska (Swedish)",
    Norwegian = "Norsk (Norwegian)",
    Finnish = "Suomi (Finnish)",
    Danish = "Dansk (Danish)",
    Hebrew = "עברית (Hebrew)",
    Ukrainian = "Українська (Ukrainian)",
    Polish = "Polski (Polish)",
    Romanian = "Română (Romanian)",
    Czech = "Čeština (Czech)",
    Hungarian = "Magyar (Hungarian)",
    Greek = "Ελληνικά (Greek)",
    Serbian = "Српски (Serbian)",
    Croatian = "Hrvatski (Croatian)",
    Bulgarian = "Български (Bulgarian)",
    Slovak = "Slovenčina (Slovak)",
    Malayalam = "മലയാളം (Malayalam)",
    Sinhala = "සිංහල (Sinhala)",
    Khmer = "ភាសាខ្មែរ (Khmer)",
    Lao = "ພາສາລາວ (Lao)",
}

export enum ValidationErrorCode {
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED",
    UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE",
    INVALID_CONTENT = "INVALID_CONTENT",
    INSUFFICIENT_SPACE = "INSUFFICIENT_SPACE",
    SYSTEM_ERROR = "SYSTEM_ERROR",
}
