name: Auto Tag on Version Change

on:
    push:
        branches: [main]
        paths: ["package.json"]

jobs:
    create-tag:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2 # Fetch current and previous commit

            - name: Check if version changed
              id: version-check
              run: |
                  # Get the version from current package.json
                  CURRENT_VERSION=$(jq -r '.version' package.json)

                  # Get the version from previous commit
                  git checkout HEAD~1 -- package.json 2>/dev/null || echo "No previous package.json"
                  PREVIOUS_VERSION=$(jq -r '.version' package.json 2>/dev/null || echo "none")

                  # Restore current package.json
                  git checkout HEAD -- package.json

                  echo "Current version: $CURRENT_VERSION"
                  echo "Previous version: $PREVIOUS_VERSION"

                  if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
                    echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
                    echo "version_changed=true" >> $GITHUB_OUTPUT
                    echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
                  else
                    echo "Version unchanged"
                    echo "version_changed=false" >> $GITHUB_OUTPUT
                  fi

            - name: Create and push tag
              if: steps.version-check.outputs.version_changed == 'true'
              run: |
                  VERSION=${{ steps.version-check.outputs.new_version }}
                  TAG_NAME="v$VERSION"

                  # Configure git
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

                  # Create and push tag
                  git tag -a "$TAG_NAME" -m "Release version $VERSION"
                  git push origin "$TAG_NAME"

                  echo "✅ Created and pushed tag: $TAG_NAME"
